// =====================================================================================
// ExcelExporter's help text (build step 10, phases H2 and H4; docs/step10-help.md).
// Copyright (c) 2026 Taro Yamaka. All rights reserved. Part of ExcelExporter and under its
// licence (src/excel-exporter/LICENSE), unlike fmIDE's help text (src/help/, CC BY 4.0).
// =====================================================================================
// Plain data, shown by ExcelExporter's Help panel (js/09d-help.js, which pulls it in with
// build:include) and published as the site's help pages under /help/excel/ (tools/build-help.js).
// ExcelExporter has no command list, so its topics name buttons in words.
//
//   EXCEL_HELP_GROUPS — the groups the topics are listed under, in order.
//   EXCEL_HELP_TOPICS — { id, group, title, keywords, summary, body }, as fmIDE's topics:
//                       { p } a paragraph · { steps: [...] } numbered · { tip } · { see: [ids] }.
//                       Topic ids are letters, digits and dashes (they become page addresses).
const EXCEL_HELP_GROUPS = [
  { id: 'start',    title: 'Getting started' },
  { id: 'layout',   title: 'Arranging the workbook' },
  { id: 'inputs',   title: 'Inputs and scenarios' },
  { id: 'format',   title: 'Formatting' },
  { id: 'generate', title: 'Making the workbook' },
];

const EXCEL_HELP_TOPICS = [
  { id: 'what-is-excelexporter', group: 'start', title: 'What ExcelExporter does',
    keywords: 'introduction overview about excel workbook xlsx formulas',
    summary: 'Turns an fmIDE model into an Excel workbook with live formulas.',
    body: [
      { p: 'ExcelExporter reads a model you built in fmIDE and writes an Excel workbook (.xlsx) whose cells hold real formulas, so it calculates exactly as fmIDE does and keeps working when you change an input in Excel.' },
      { steps: [
        'Load the model: open ExcelExporter from fmIDE (it arrives by itself), drop its file on the page, or choose File → Open Model….',
        'Check the period labels and the file name (⚙ Settings → Workbook).',
        'Arrange the tabs (on the left) and the rows (on the right), if you like.',
        'Press ⬇ Generate .xlsx, at the top right.',
      ] },
      { p: 'Every file you can import or export, and every reset, is in the two menus at the top: File (the model, Start Over) and Layout (this model\'s layout, module layouts, your Excel style). Pointing at a button or a menu item says what it does.' },
      { p: 'Everything happens in your browser: nothing is uploaded, and it works offline.' },
      { p: 'What\'s new, at the top of this Help panel, lists every update to ExcelExporter, newest first, each with what changed, why and how to use it. A dot on ❓ Help means there is something you haven\'t seen yet.' },
      { p: 'This Help panel opens with ❓ or F1. Press ⤢ at its top for a wider reading view (⤡ brings it back), or drag its left edge to any width; it remembers the width.' },
      { see: ['load-model', 'generate'] },
    ] },
  { id: 'load-model', group: 'start', title: 'Loading a model',
    keywords: 'load open file fmide json drop sample paste system workspace from fmide reload refresh',
    summary: 'Open ExcelExporter from fmIDE, or open a .fmide document, or a system or workspace file saved by fmIDE.',
    body: [
      { p: 'Opened from fmIDE (File → Open ExcelExporter), ExcelExporter loads the model fmIDE has open by itself — no file to save first. After changing the model in fmIDE, choose File → ↻ From fmIDE here (or Open ExcelExporter in fmIDE again) to load it as it is now. A change to numbers keeps your layout; adding or deleting a rectangle starts a new layout, as loading a changed file does (a module\'s tab keeps its remembered layout). The Excel layouts its canvas templates carry come along too.' },
      { p: 'Or open a saved file:' },
      { steps: [
        'In fmIDE, save your model (File → Save gives a .fmide file).',
        'Here, drop the file on the box (or anywhere on the page), or click the box to choose it. Once a model is loaded, File → Open Model… opens another.',
      ] },
      { p: 'A system file (Save System) or a workspace (Export Workspace) works too, and File → Paste JSON… takes a model\'s text. The number formats you set in fmIDE come across; how cells look is your own Excel style (⚙ Settings → Excel Style).' },
      { p: 'To see how it works first, press ▶ Load Sample Model (also in the File menu).' },
      { p: 'Your layout (tabs, rows, names, order) is remembered in this browser for each model, so loading the same model again brings it back.' },
      { see: ['what-is-excelexporter', 'remembered', 'back-to-fmide'] },
    ] },
  { id: 'back-to-fmide', group: 'start', title: 'Going back to fmIDE',
    keywords: 'back fmide return window close',
    summary: '← Back to fmIDE, at the top left.',
    body: [
      { p: '← Back to fmIDE returns to fmIDE. When ExcelExporter has its own window, it closes that window (your layout is kept, and fmIDE sends its model again next time you open ExcelExporter; it asks first only when the model shown is a file you opened here). On an iPad, where ExcelExporter took fmIDE\'s place, it goes back to fmIDE.' },
      { p: 'File → Start Over clears the model loaded here. Saved layouts are kept.' },
      { see: ['remembered'] },
    ] },
  { id: 'periods-output', group: 'layout', title: 'Period columns and the file name',
    keywords: 'period columns header label year quarter month frequency file name number format',
    summary: 'How the period columns are labelled, the fallback number format and the file name.',
    body: [
      { p: 'Each period of fmIDE\'s timeline becomes a column. ⚙ Settings → Workbook only decides how the columns are labelled: the first label (for example 2027) and the frequency (annual, quarterly or monthly).' },
      { p: 'The fallback number format is used for cells whose rectangle has no number format of its own.' },
      { p: 'The output file name is the name of the downloaded workbook.' },
      { see: ['formats', 'generate'] },
    ] },
  { id: 'tabs', group: 'layout', title: 'Tabs',
    keywords: 'tab sheet worksheet rename reorder add delete',
    summary: 'One Excel tab per fmIDE canvas to start with; rename, reorder, add or delete them.',
    body: [
      { p: 'The Tabs panel, on the left, lists the workbook\'s tabs in order. Each fmIDE canvas starts as its own tab. Rename a tab by typing its name, move it with ↑ and ↓, add one with + Add Tab, or delete one with 🗑 (its rows move to the first remaining tab).' },
      { p: 'A tab\'s row count (for example "3 rows") takes you to its rows. Which rows go on which tab is set in the Rows panel.' },
      { see: ['rows', 'module-layouts', 'inputs-tab'] },
    ] },
  { id: 'module-layouts', group: 'layout', title: 'Modules remember their layout',
    keywords: 'module template reuse remember layout forget export import recipe repeat block instance vintage',
    summary: 'Arrange a module\'s tab once: every model that uses the module starts with the same layout.',
    body: [
      { p: 'A tab marked 🧩 comes from a module: a canvas you added from a template in fmIDE (recipes build them too). When you change such a tab — its name, the order of its rows, labels, blank or label rows, Include, formats, indents — ExcelExporter remembers that layout for the module.' },
      { steps: [
        'The next model with the same module, laid out here for the first time, starts with that layout. Rows are matched by rectangle name; rectangles the layout doesn\'t know go where the automatic sort puts them.',
        'A model you have already arranged keeps its own layout.',
        'Forget, on the tab, stops the module\'s layout being used for new models.',
        'Layout → Export Module Layouts saves them all as a file; Import Module Layouts… reads one, for example on another computer.',
      ] },
      { p: 'Export Module Layouts saves every module remembered in this browser, from every model you have arranged here — not only the model loaded now. Each is named after its template, not after your canvas. That is expected: fmIDE\'s Attach Excel layout… takes just the one for its template.' },
      { see: ['template-layouts', 'remembered'] },
      { p: 'A module used as a block in fmIDE remembers the layout of its instances\' tabs too, the same way (their tab names aren\'t remembered). In a vertical block, rows are matched by vintage, Total and shared row; a longer timeline\'s extra vintages go after the last one. On an instance tab, "Lay out the other instances like this" gives the block\'s other instances in this model the same layout — for any block, from a template or not.' },
      { tip: 'Rows you move to another tab stay in the module\'s own tab when the layout is used again. The rows of a block inside a block go where the automatic sort puts them.' },
      { see: ['tabs', 'tree-view', 'blocks'] },
    ] },
  { id: 'template-layouts', group: 'layout', title: 'A template\'s attached layout',
    keywords: 'template attach attachment excel layout module pack share fmide family version',
    summary: 'Attach a module\'s layout to its template in fmIDE, so it travels with the template.',
    body: [
      { p: 'A canvas template in fmIDE can carry the Excel layout of its module, so that whoever uses the template — another person, or you in another browser — gets the same tab layout here.' },
      { steps: [
        'Here, arrange the module\'s tab (marked 🧩). The layout is remembered.',
        'Choose Layout → Export Module Layouts. The file holds every remembered module; that is fine.',
        'In fmIDE, open the Templates window, choose that template\'s version and press 📎 Attach Excel layout…, then pick the file. fmIDE takes only the layout for that template.',
      ] },
      { p: 'fmIDE only carries the layout: it never reads or changes it. It goes with the template in workspaces, .fmide documents, template files and library packs; Save as new version carries it on. A model file (Save System) carries no templates, so no attached layout.' },
      { p: 'When it is used here:' },
      { steps: [
        'Only when the model comes from fmIDE, or you load a .fmide document or a workspace (they carry their templates).',
        'Only for a new layout: a model you have already arranged here keeps its own layout.',
        'Only when you have no remembered layout of your own for that module: yours wins.',
        'The layout of the version the canvas was made from, else the newest version that has one.',
      ] },
      { p: 'The tab then says "layout from the template". Change it and your change becomes your own remembered layout.' },
      { tip: 'On your own computer your remembered layout usually comes first. To see the attached one: press Forget on the module\'s tab, choose Layout → Reset Mapping to Defaults…, then load the .fmide document or workspace again.' },
      { see: ['module-layouts', 'remembered'] },
    ] },
  { id: 'remembered', group: 'layout', title: 'What is remembered, and which layout wins',
    keywords: 'remember saved memory start over reset forget priority order which layout mapping module template browser clear',
    summary: 'Three things are kept in this browser; Start Over keeps all of them.',
    body: [
      { p: 'ExcelExporter keeps three things in this browser:' },
      { steps: [
        'A layout for each model you have arranged here — saved as you go. Layout → Reset Mapping to Defaults… discards it for the loaded model. Layout → Export Mapping saves it as a file.',
        'A layout for each module (a canvas from a template), saved whenever you change that module\'s tab or a block instance\'s tab, in any model. Forget, on the tab, discards it. Layout → Export Module Layouts saves them all as a file.',
        'Your Excel style, the same for every model. Reset to Defaults… (⚙ Settings → Excel Style) puts it back.',
      ] },
      { p: 'File → Start Over only empties this page. It keeps all three, so loading a model you arranged before brings its layout straight back.' },
      { p: 'When you load a file, the layout comes from the first of these that exists:' },
      { steps: [
        'The layout saved for this model. If there is one, it is used as it is, and nothing below is looked at.',
        'Otherwise a new layout is built. Each module\'s tab takes your own remembered layout for that module…',
        '…or, without one, the layout attached to its template (only from a .fmide document or workspace)…',
        '…or, without that, the automatic sort. Tabs not from a module always start from the automatic sort.',
      ] },
      { p: 'Block instance tabs follow the same order, using the module\'s instance layout.' },
      { tip: 'Export Mapping is one model\'s whole workbook layout (tabs, rows, Inputs tab, scenarios, settings). Export Module Layouts is the per-module layouts, for reuse in other models and for fmIDE\'s Attach Excel layout….' },
      { see: ['module-layouts', 'template-layouts', 'formats', 'generate'] },
    ] },
  { id: 'rows', group: 'layout', title: 'Rows: what goes where',
    keywords: 'rows order include constant section label move sort custom row group by canvas tab',
    summary: 'Every rectangle becomes a labelled row: choose its tab, place, label, and whether it is included.',
    body: [
      { p: 'Each value rectangle becomes one row. Operators, aliases and period shifts don\'t get rows: they become part of the formulas.' },
      { p: 'The Rows panel shows the rows as a Tree (where it starts), as a table per Excel tab, or as a table per canvas. For each row you can:' },
      { steps: [
        'change its label;',
        'move it to another tab or up and down;',
        'untick Include to leave it out;',
        'tick Constant to put a small fixed number (a sign flip, ×1000) straight into the formulas instead of giving it a row.',
      ] },
      { p: 'To move several rows at once, select them — in the Tree click, Ctrl-click or Shift-click; in the tables tick the box at the left of each — and use the bar that appears above them.' },
      { p: 'Sort reorders rows: by calculation order (inputs first, or results first), by position on the canvas, or alphabetically; press Apply. + Label Row adds a label or blank row below the selected one; edit it in the Tree (double-click to rename, PERIODS to repeat the period labels on it, 🎨, 🗑) or in the By Excel Tab table.' },
      { p: 'With Sections ticked, each tab has INPUTS, CALCULATIONS and OUTPUTS bands. Untick it for one free list per tab.' },
      { p: 'A Block In or Block Out tag shows the rectangle\'s port role in fmIDE\'s Block feature. Constant works inside a block too.' },
      { see: ['tree-view', 'blocks', 'tabs'] },
    ] },
  { id: 'tree-view', group: 'layout', title: 'The Tree View',
    keywords: 'tree view select rename right-click menu indent format row shift ctrl',
    summary: 'Every tab\'s rows as one list: select, rename, indent, format and move them.',
    body: [
      { p: 'The Tree, the Rows panel\'s first view, shows every row of each tab in order, including left-out ones (dimmed), as they will appear in Excel. Click a tab\'s name to fold it.' },
      { steps: [
        'Click a row to select it. Ctrl-click (Cmd-click on a Mac) adds or removes one, and Shift-click selects a range.',
        'Double-click a row\'s label to rename it.',
        'Right-click rows for every command: move, include, constant, scenarios, indent, format, move to another tab.',
        'Alt+Shift+→ and Alt+Shift+← indent the selected labels, like Excel\'s Increase Indent.',
        '🎨 on a row gives it its own fill, font colour, bold, border and number format in Excel. Reset to the Excel style takes it off.',
      ] },
      { p: 'On a tablet, press and hold a row for its menu, and double-tap to rename.' },
      { see: ['rows', 'formats'] },
    ] },
  { id: 'blocks', group: 'layout', title: 'Blocks in the workbook',
    keywords: 'block instance vertical vintage total unpacked',
    summary: 'A block is unpacked into its own rows; a vertical block into one set per period, plus a total.',
    body: [
      { p: 'A block used in fmIDE gets its own group of rows in the workbook ("Block instance —"), once per instance, since each instance calculates on its own.' },
      { p: 'The block\'s own box never gets a row: its rectangles do. A block input inside it reads whatever is wired into that instance\'s input (0 when nothing is).' },
      { p: 'A vertical block gets a set of rows for each period (V1, V2, …) and a Σ Total row for each output that combines them with SUM, MAX, MIN, AVERAGE or PRODUCT, as its output does in fmIDE. A row that is the same in every set is written once (Shared). With many periods that can be many rows: reorder, rename or leave them out like any other.' },
      { p: 'A block that uses itself, directly or through another block, is left out; the yellow list under the Generate button says so.' },
      { p: 'Arrange one instance\'s tab, then use "Lay out the other instances like this" on it (in the Tabs panel) to give the block\'s other instances the same layout. A block added from a template in fmIDE also remembers that layout for the next model.' },
      { see: ['rows', 'module-layouts'] },
    ] },
  { id: 'inputs-tab', group: 'inputs', title: 'The Inputs tab',
    keywords: 'inputs tab gather assumptions separate group order',
    summary: 'Gather every typed-in number on one tab, with the other tabs linking to it.',
    body: [
      { p: 'Tick Gather inputs on a separate tab (Inputs & scenarios, on the left) to put every input (a rectangle with no arrow in) on its own tab. Its original row stays where it was and links to the Inputs tab, shown in the Links format.' },
      { p: 'Choose the tab\'s name, how its rows are grouped (by Excel tab, by canvas, or not at all) and their order. Re-apply layout rebuilds the grouping from these settings.' },
      { see: ['scenarios', 'rows'] },
    ] },
  { id: 'scenarios', group: 'inputs', title: 'Scenarios and global cases',
    keywords: 'scenario case global switch sensitivity base high low',
    summary: 'Give an input several values and choose which one the workbook runs.',
    body: [
      { steps: [
        'Turn on the Inputs tab (Inputs & scenarios, on the left).',
        'On a row of the Inputs tab (in the Rows panel), tick scenarios — or select several rows and use ≡ Add Scenarios. That input gets several values, one per scenario: the first is fmIDE\'s value, the others start empty for you to fill in Excel. Scenarios each sets how many.',
        'A Scenarios tab in the workbook picks which scenario each input uses.',
      ] },
      { p: 'With Global cases above 0, each case picks one scenario for every input, and a single Global Case cell chooses the case the whole workbook runs.' },
      { see: ['inputs-tab'] },
    ] },
  { id: 'formats', group: 'format', title: 'How the workbook looks',
    keywords: 'format role colour fill font border sides size bold number format style excel style export import reset row',
    summary: 'Your own Excel style sets how every cell looks; fmIDE sets the number formats.',
    body: [
      { p: 'Every cell takes its look from one of seven roles in your Excel style (⚙ Settings → Excel Style, or Layout → Excel Style…): Inputs, Calculations, Links, Headers, Section Headers, Labels and Notes.' },
      { steps: [
        'For each role, pick the fill, the font colour, bold, the font size (blank uses Excel\'s default) and the border: its style, colour and which sides.',
        'Changes are saved in this browser and used for every model you load here.',
        'Export Excel Style saves it as a file; Import Excel Style… reads one, for example on another computer.',
        'Reset to Defaults… puts every role back to ExcelExporter\'s built-in look.',
        'Point at a role\'s name to see which cells it covers.',
      ] },
      { p: 'In the Tree View, 🎨 on a row gives just that row its own look in this workbook.' },
      { p: 'A cell\'s fill, font colour, bold and border come from the first of these that is set:' },
      { steps: [
        'the row\'s own format (🎨 in the Tree View), part of this model\'s layout;',
        'your Excel style for the row\'s role.',
      ] },
      { p: 'fmIDE\'s canvas colours, fonts and borders never reach Excel.' },
      { p: 'A cell\'s number format comes from the first of these that is set:' },
      { steps: [
        'the row\'s own format, if you gave it a number format;',
        'the rectangle\'s own 🎨 format in fmIDE;',
        'fmIDE\'s Inputs or Calculations format, whichever the rectangle is;',
        'the fallback number format (⚙ Settings → Workbook).',
      ] },
      { see: ['tree-view', 'periods-output', 'remembered'] },
    ] },
  { id: 'differences', group: 'generate', title: 'Where the workbook differs from fmIDE',
    keywords: 'differences yellow list warning na n/a error loop broken too long show all hide dismiss',
    summary: 'The yellow list under Generate says where Excel can\'t calculate as fmIDE does.',
    body: [
      { p: 'The workbook calculates exactly as fmIDE does. Where it can\'t, a yellow list at the top of the page, under the Generate button, says where, before you download. For example:' },
      { steps: [
        'something broken in the model, such as an alias to a rectangle that was deleted, a loop, or two arrows into one rectangle (fmIDE shows "?");',
        'a row you left out that other rows read;',
        'a function fmIDE can\'t calculate, or a formula too long for Excel (the cell shows #N/A).',
      ] },
      { p: 'The download still works. Fix the model in fmIDE, or the layout here, and the list goes away.' },
      { p: 'A long list shows its first three lines: Show all opens the rest, and × hides the list until something in it changes.' },
      { tip: 'Many lines often come from one place, such as one operator with nothing wired into it: fix that in fmIDE and they all go.' },
      { see: ['generate'] },
    ] },
  { id: 'generate', group: 'generate', title: 'Generating and saving the layout',
    keywords: 'generate download xlsx mapping export import reset layout',
    summary: 'Download the workbook; save, share or reset the layout.',
    body: [
      { p: '⬇ Generate .xlsx, at the top right, writes the workbook and downloads it. Excel works out every formula when it opens the file. Formulas, number formats and how cells look all carry through.' },
      { p: 'Your layout is saved in this browser as you go. In the Layout menu, Export Mapping saves this model\'s whole layout to a file (to share it, or keep it safe), and Import Mapping… loads one. Reset Mapping to Defaults… discards the layout for this model and starts again; module layouts and your Excel style are kept.' },
      { see: ['differences', 'rows', 'remembered'] },
    ] },
];
