// =====================================================================================
// fmIDE's help text (build step 10, docs/step10-help.md).
// Copyright 2026 Taro Yamaka. Licensed under CC BY 4.0 (https://creativecommons.org/licenses/by/4.0/,
// docs/LICENSE-CC-BY-4.0.txt), unlike the code around it.
// =====================================================================================
// Plain data, shown by the Help panel (src/fmide/js/01b-help.js) and found by its search and
// the Command Launcher, and published as the site's help pages, /help (tools/build-help.js).
// Written for people who use fmIDE, in plain English. Topic and group ids are letters, digits
// and dashes (they become page addresses).
//
//   HELP_GROUPS   — the groups the topics are listed under, in order.
//   HELP_TOPICS   — { id, group, title, keywords, summary, body }. body is a list of blocks:
//                   { p: text } a paragraph · { steps: [text…] } numbered steps ·
//                   { tip: text } a tip · { see: [topic ids] } related topics.
//                   In any text, {cmd:commandId} shows that command as a button that runs it.
//   COMMAND_HELP  — one plain sentence for every command (a test checks none is missing).
//   OPERATOR_HELP — one sentence per operator, by its catalogue id (src/shared/operators.js),
//                   for the Insert Operator commands.
// When a feature changes, change its topic here in the same pull request.
const HELP_GROUPS = [
  { id: 'start',     title: 'Getting started' },
  { id: 'build',     title: 'Building a model' },
  { id: 'time',      title: 'Periods and time' },
  { id: 'canvases',  title: 'Canvases, blocks, plugs' },
  { id: 'templates', title: 'Templates and recipes' },
  { id: 'functions', title: 'Functions' },
  { id: 'sharing',   title: 'Sharing and the library' },
  { id: 'files',     title: 'Files and saving' },
  { id: 'format',    title: 'Formatting' },
  { id: 'excel',     title: 'To Excel' },
  { id: 'faster',    title: 'Working faster' },
  { id: 'macros',    title: 'Macros' },
  { id: 'touch',     title: 'Touch' },
];

const HELP_TOPICS = [
  // ---------- Getting started ----------
  { id: 'what-is-fmide', group: 'start', title: 'What fmIDE is',
    keywords: 'introduction overview about start begin model graph',
    summary: 'Build a financial model as a picture of boxes and arrows, then turn it into a live Excel workbook.',
    body: [
      { p: 'In fmIDE a model is a drawing. Each number is a box, called a rectangle. Arrows show where numbers come from, and small boxes called operators (+ − × ÷ and more) combine them. fmIDE works out every value for you, for every period of your timeline.' },
      { p: 'Because the logic is a drawing, you can see at a glance how a result is made, check it, and reuse parts of it as templates.' },
      { p: 'When the model is ready, ExcelExporter turns it into an Excel workbook with real formulas that calculate exactly as fmIDE does.' },
      { p: 'Everything stays on your computer: nothing is uploaded, and fmIDE works offline.' },
      { see: ['first-model', 'finding-your-way', 'to-excel'] },
    ] },
  { id: 'first-model', group: 'start', title: 'Your first model in five minutes',
    keywords: 'tutorial quick start example price quantity revenue multiply beginner',
    summary: 'Price × quantity = revenue: three rectangles, one operator, three arrows.',
    body: [
      { p: 'This builds Revenue = Price × Quantity.' },
      { steps: [
        'Press {cmd:addRect}. A rectangle appears with its text ready to type. Type Price, press Shift+Enter, type 10, press Shift+Enter, type $/t, then press Enter. The three lines are the name, the value and the unit.',
        'Add a second rectangle the same way: Quantity, 5, t.',
        'Add a third: Revenue, with no value (just the name, then Enter).',
        'Press {cmd:addOperator} and choose × in the list that opens.',
        'Draw an arrow from Price to the × operator: point at Price, then drag from one of the small dots on its edges onto the operator. With a mouse, you can also drag with the right button from anywhere on Price.',
        'Draw an arrow from Quantity to the operator, and one from the operator to Revenue.',
        'Press {cmd:evaluate} (F9). Revenue shows = 50, and its unit, $, is worked out for you.',
      ] },
      { tip: 'Values are worked out when you press Evaluate (F9). After a change, press it again to see the new numbers.' },
      { see: ['rectangles', 'operators', 'arrows', 'periods'] },
    ] },
  { id: 'finding-your-way', group: 'start', title: 'Finding your way around',
    keywords: 'ribbon tabs canvas tabs screen layout interface help search launcher',
    summary: 'The ribbon at the top, the canvas tabs, the canvas, the Command Launcher and this Help panel.',
    body: [
      { p: 'The ribbon at the top holds every command, in tabs: File (documents, templates, the library), Home (the everyday commands), Insert (rectangles, operators, functions), Arrange, Model (periods and canvases), View and Macros. Point at a button to see what it does.' },
      { p: 'Below the ribbon are the canvas tabs. A model can have several canvases, like the sheets of a workbook; + adds one.' },
      { p: 'The big area is the canvas, where you build. Scroll it to move around.' },
      { p: 'To see more or less of it, zoom: hold Ctrl (Cmd on a Mac) and turn the mouse wheel, or pinch on a trackpad (or with two fingers on a tablet); Ctrl + = and Ctrl + − zoom in and out, and Ctrl + 0 goes back to 100%. The control at the bottom-right shows the zoom: − and + step it, and the percentage opens a menu with {cmd:zoomFit} and {cmd:zoomSelection}. Each canvas keeps its own zoom, and everything works the same at any zoom.' },
      { p: 'To find a command by name, press {cmd:openLauncher} (Ctrl+K, or Cmd+K on a Mac), type part of its name and press Enter. Help topics are found there too.' },
      { p: 'This Help panel opens with F1, with ❓ at the top right, or with {cmd:openHelp}. You can keep working while it is open.' },
      { p: 'What\'s new, at the top of the Help panel (or {cmd:openWhatsNew}), lists every update, newest first: what changed, why, and how to use it. A dot on ❓ means there is something you haven\'t seen yet.' },
      { p: 'To read more comfortably, press ⤢ at the top of the panel: it widens to a reading view, and ⤡ brings it back. Or drag its left edge to any width; a double-click on the edge goes back to the usual width. Help remembers the width.' },
      { see: ['launcher-shortcuts', 'canvases'] },
    ] },

  // ---------- Building a model ----------
  { id: 'rectangles', group: 'build', title: 'Rectangles: name, value and unit',
    keywords: 'rectangle node box value input calculation name unit uom edit text many list several paste add many chain',
    summary: 'A rectangle holds one number: typed in (an input) or worked out from its arrows (a calculation).',
    body: [
      { p: 'A rectangle has three lines: its name, its value and its unit of measure (for example t, $ or $/t). Double-click a rectangle to change them. Press Shift+Enter for the next line and Enter when you are done.' },
      { p: 'To add several at once, use {cmd:addManyRects}: type a name in each row and press Enter for the next (value and unit are optional), or paste a list, one name per line, or columns copied from Excel. Choose a column, a row or a grid and the gap between them; they are added in one step, and selected so you can drag them into place. A name already on the canvas is marked, but still allowed.' },
      { p: 'While typing in a rectangle, Ctrl+Enter (Cmd+Enter on a Mac) saves it and starts a new one just below, with the same gap as the one above it, so you can type a list straight down the canvas.' },
      { p: 'A rectangle with no arrow coming in is an input: you type its value. A rectangle fed by an arrow is a calculation: its value comes from the arrow, and fmIDE shows it after {cmd:evaluate}.' },
      { p: 'Units are worked out for you. $/t × t gives $, and adding t to $ is flagged.' },
      { p: 'The small buttons on a selected rectangle:' },
      { steps: [
        '🔌 plugs: feed this rectangle to operators on other canvases by name.',
        '⇄ marks the rectangle as a block input or output.',
        '🎨 gives it its own format.',
        '🕒 chooses which periods use its own number.',
        '📈 draws its value across periods.',
      ] },
      { see: ['operators', 'arrows', 'values-over-time', 'plugs-sockets', 'formats'] },
    ] },
  { id: 'operators', group: 'build', title: 'Operators',
    keywords: 'operator add subtract multiply divide plus minus times sum min max average abs iferror power modulo ln log logarithm exp exponential sqrt square root int trunc whole number',
    summary: 'Small boxes that combine the values of the arrows coming in: + − × ÷ and more.',
    body: [
      { p: '{cmd:addOperator} adds one and asks which. The Insert tab has every operator as its own button, in the groups Arithmetic, Compare and Excel Functions. Double-click an operator to change it.' },
      { p: '+ and × take any number of arrows. For − ÷ ^ and %, the order counts: inputs are taken from left to right by where they sit on the canvas, and a small number on each arrow shows its place.' },
      { p: 'min, max, ave (average) and abs work like their Excel functions. iferror uses its first input, or the second one where the first has an error.' },
      { p: 'ln, exp, sqrt, int and trunc take one input each, like Excel\'s LN, EXP, SQRT, INT and TRUNC. The log of 0 or less and the square root of a negative number are errors ("?"). int rounds down (−2.5 gives −3), trunc cuts the fraction off (−2.5 gives −2). The results of ln, exp and sqrt have no unit.' },
      { p: 'Draw the operator\'s result into a rectangle, so it has a name and appears in Excel.' },
      { see: ['arrows', 'timing-conditions', 'functions'] },
    ] },
  { id: 'arrows', group: 'build', title: 'Drawing arrows',
    keywords: 'arrow connect connection edge link wire draw delete',
    summary: 'Arrows carry values from one box to the next.',
    body: [
      { steps: [
        'Point at a box, or select it: small dots appear on its edges.',
        'Drag from a dot and drop on the box that should receive the value.',
      ] },
      { p: 'With a mouse, dragging with the right button from anywhere on a box does the same.' },
      { p: 'To delete an arrow, click it and press Delete.' },
      { p: 'Some boxes have named inputs, such as if (condition, then, else), round (value, digits) and your own functions. Drop the arrow on the dot you mean, or on the box to fill the first empty input.' },
      { see: ['operators', 'touch'] },
    ] },
  { id: 'aliases', group: 'build', title: 'Aliases',
    keywords: 'alias link reference copy show another rectangle reuse',
    summary: 'An alias shows another rectangle\'s value somewhere else, without a long arrow.',
    body: [
      { p: 'An alias is a stand-in for a rectangle on this canvas or on another one. It always shows the same value, and arrows can start from it.' },
      { p: '{cmd:addAlias} asks which rectangle it should show. With a mouse, you can also drag a rectangle while holding Alt (Option on a Mac) to make an alias of it.' },
      { p: '🔗 on an alias changes the rectangle it shows.' },
      { see: ['canvases', 'plugs-sockets'] },
    ] },
  { id: 'arranging', group: 'build', title: 'Moving, copying and arranging',
    keywords: 'move drag select selection copy paste duplicate align distribute undo redo delete snap equal spacing gap even guide',
    summary: 'Select, move, copy, line up and undo.',
    body: [
      { p: 'Drag a box to move it. To select several, drag a box around them on empty canvas, or hold Shift or Ctrl while you click.' },
      { p: '{cmd:copy} and {cmd:paste} copy boxes with the arrows between them. With a mouse, you can also drag while holding Ctrl to duplicate. Pasted boxes land in free space.' },
      { p: 'While you drag, a box snaps into line with the boxes around it (a blue line shows which edge or middle lines up), and to equal spacing: next to two boxes side by side, or one above the other, it snaps where the gaps are equal, after them, before them or halfway between them. Pink bars mark the equal gaps. Only the boxes in its row or column count. Hold Alt after you start dragging to move it freely, without snapping.' },
      { p: 'The Arrange tab lines up the selection ({cmd:alignLeft}, {cmd:alignTop} and others) and spaces it evenly ({cmd:distH}, {cmd:distV}).' },
      { p: '{cmd:undo} and {cmd:redo} step back and forward through your changes.' },
    ] },

  // ---------- Periods and time ----------
  { id: 'periods', group: 'time', title: 'Periods and the timeline',
    keywords: 'period periods timeline year month quarter column time manage',
    summary: 'One timeline shared by every canvas: the model is worked out for each period.',
    body: [
      { p: 'A model runs over a timeline of periods (for example FY25, FY26, FY27), shared by every canvas. In Excel each period becomes a column.' },
      { steps: [
        'Open {cmd:managePeriods} to add periods, remove the last one, or rename them.',
        'The canvas shows one period at a time. Move between them with {cmd:prevPeriod} and {cmd:nextPeriod}.',
      ] },
      { p: 'An input keeps the same value in every period unless you give it values per period.' },
      { see: ['period-shifts', 'values-over-time'] },
    ] },
  { id: 'period-shifts', group: 'time', title: 'Period shifts: last period and next period',
    keywords: 'period shift prior previous last next period lag opening closing balance corkscrew',
    summary: 'Read a value from an earlier (or later) period, for example last year\'s closing balance.',
    body: [
      { p: 'A period shift passes on a value from another period. Set to −1, which is the usual choice, it passes on the previous period\'s value.' },
      { steps: [
        'Press {cmd:addPeriodShift}.',
        'Draw an arrow from the rectangle you want last period\'s value of (for example Closing balance) into the shift.',
        'Draw an arrow from the shift to where it is used (for example Opening balance).',
        'Double-click the shift to change how many periods it moves.',
      ] },
      { p: 'In the first period there is no earlier value. Give the opening balance its own number there: its 🕒 button chooses which periods use the typed number, and the others take the arrow. Or use if(period = 1, …), see Timing, conditions and rounding.' },
      { see: ['periods', 'timing-conditions'] },
    ] },
  { id: 'values-over-time', group: 'time', title: 'A value that changes over time',
    keywords: 'per period values curve draw growth series 📈 🕒 own number',
    summary: 'Give an input a different value in each period, or use its own number only in some periods.',
    body: [
      { p: '📈 on an input rectangle opens a small chart. Draw the values across the periods, or type them separated by commas.' },
      { p: 'The chart shows every period at once. Drag the window\'s bottom-right corner to make it bigger and the chart grows with it; with many periods, type exact values in the boxes below the chart.' },
      { p: '🕒 chooses the periods where the rectangle uses its own typed number. In the other periods it takes what its arrow brings in, for example a balance carried forward.' },
      { see: ['periods', 'period-shifts'] },
    ] },
  { id: 'timing-conditions', group: 'time', title: 'Timing, conditions and rounding',
    keywords: 'period number if condition then else equal not equal and or not round roundup rounddown compare choose scenario switch case index',
    summary: 'The period number, if, choose, comparisons, and, or, not, and the three kinds of rounding.',
    body: [
      { p: 'period gives the period number: 1, 2, 3 and so on.' },
      { p: 'if takes three inputs: condition, then and else. Only the branch taken is worked out.' },
      { p: 'For example, a closing balance that starts from an opening number:' },
      { steps: [
        'Make Opening, typed in.',
        'Make an if.',
        'Feed its condition from period = 1.',
        'Feed then from Opening, and else from last period\'s Closing (through a period shift).',
      ] },
      { p: '= ≠ < > ≤ ≥ compare two values and give 1 (true) or 0 (false). and, or and not combine them.' },
      { p: 'round, roundup and rounddown take a value and a number of digits, like Excel\'s ROUND.' },
      { p: 'choose picks one of several values by a number, like Excel\'s CHOOSE: an index of 2 gives choice 2. It suits a scenario switch (1 base, 2 upside, 3 downside). Only the choice picked is worked out; an index below 1 or past the last choice is an error ("?").' },
      { p: 'if, round and choose show a labelled dot for each input. Drop an arrow on the one you mean. choose always shows one empty choice at the end for the next arrow.' },
      { see: ['operators', 'period-shifts'] },
    ] },

  // ---------- Canvases, blocks, plugs ----------
  { id: 'canvases', group: 'canvases', title: 'Canvases',
    keywords: 'canvas tab sheet page new rename delete move switch next previous go to shortcut alt pagedown pageup',
    summary: 'Split a model into canvases, like the sheets of a workbook.',
    body: [
      { p: 'Each canvas is a tab above the canvas area, and becomes its own tab in Excel.' },
      { p: '{cmd:newCanvas} (or + at the end of the tabs) adds one. Double-click a tab to rename it, and drag it to move it.' },
      { p: 'The Model tab also has {cmd:renameCanvas}, {cmd:deleteCanvas} and {cmd:clearCanvas}.' },
      { p: 'To move between canvases from the keyboard, use {cmd:nextCanvas} (Alt+Page Down) and {cmd:prevCanvas} (Alt+Page Up); they go round from the last tab to the first. On a Mac, Option+Page Down. You can choose other keys in Keyboard Shortcuts.' },
      { p: 'Values can travel between canvases through aliases, or plugs and sockets.' },
      { see: ['aliases', 'plugs-sockets', 'blocks'] },
    ] },
  { id: 'blocks', group: 'canvases', title: 'Blocks: a canvas used as a building block',
    keywords: 'block instance input output reuse vertical vintage reducer sum index',
    summary: 'Build a calculation once on its own canvas, then use it many times as a single box.',
    body: [
      { p: 'Any canvas can become a block: mark its rectangles as inputs and outputs with their ⇄ button. On another canvas, {cmd:addBlock} adds the block as one box, with its inputs on the left and its outputs on the right. Draw arrows into its inputs and out of its outputs.' },
      { p: 'Vertical blocks run once per period, for example one per year of capital spending, each depreciating on its own. Their results are combined into each output: added up by default, or max, min, average or product, chosen with the output rectangle\'s Σ chip.' },
      { p: 'To make a block vertical, tick Vertical when you add it (or through 🔗 Change block).' },
      { p: 'On a vertical block, each input is either the same for every instance or read at that instance\'s own period.' },
      { see: ['canvases', 'templates'] },
    ] },
  { id: 'plugs-sockets', group: 'canvases', title: 'Plugs and sockets',
    keywords: 'plug socket connect across canvases name automatic alias ⚡ 🔌',
    summary: 'Connect canvases by name: a rectangle\'s plug feeds every operator whose socket has that name.',
    body: [
      { steps: [
        'On the rectangle that gives the value, click 🔌 and type a name, for example Income Tax.',
        'On the operator that should receive it (on any canvas), click ⚡ and type the same name.',
      ] },
      { p: 'fmIDE connects them for you, drawing an automatic alias on the socket\'s canvas.' },
      { p: 'A rectangle can have several plugs.' },
      { p: 'When more than one plug feeds a socket, their values are added together. The socket shows ⚡ name ×2 in amber as a warning, since that can double a number by accident.' },
      { p: 'Plugs and sockets are how the canvases built by a recipe connect.' },
      { see: ['canvases', 'recipes'] },
    ] },

  // ---------- Templates and recipes ----------
  { id: 'templates', group: 'templates', title: 'Templates',
    keywords: 'template save reuse insert add canvas module system library excel layout attach attachment group expand collapse all tree',
    summary: 'Save a canvas (or the whole model) to reuse it, and add it again in one click.',
    body: [
      { p: '{cmd:openTemplates} lists your templates, with a search box: type part of a name, then press Enter to add it.' },
      { p: 'The list is a tree of groups. Click a group to open or close it; ▾ Expand all and ▸ Collapse all, under the search box, open or close every group at once. ✎ Edit info and 🗑 Delete sit beside the selected template\'s name; 🧹 Remove duplicates… and 🗑 Clear all templates, under the list.' },
      { p: 'To save one, use + Save Canvas as Template (the canvas you are on) or + Save System as Template (the whole model) in the same window. Give it a name, a group and a short description.' },
      { p: 'A canvas template can be added to a new canvas or to the current one. A system template adds its canvases alongside yours, or replaces the model. Canvases that came from a canvas template stay linked to it in a system template, so when the system is added back they still offer that template\'s updates and ExcelExporter still lays them out as modules.' },
      { p: 'Templates are kept in fmIDE and travel inside your documents.' },
      { p: '{cmd:removeDuplicateTemplates} tidies up copies that built up over time.' },
      { p: 'A canvas template can carry its Excel layout: select it and choose 📎 Attach Excel layout…, then pick a file saved by ExcelExporter\'s Export Module Layouts. The layout then goes wherever the template goes — your documents, new versions and packs you share — and ExcelExporter uses it for that module\'s tab unless you have arranged the tab yourself. fmIDE only carries it; Remove takes it off.' },
      { p: 'A canvas or system template can carry an fmGraph board the same way: in fmGraph, open a model made from the template and choose Boards → Export for a template…, then select the template here and choose 📈 Attach fmGraph board…. A canvas template\'s board shows only its own canvas; a system template\'s, the whole model. The board goes along with the template, in packs too. With fmGraph opened from here, its Boards → Attach to template… does it in one step: fmIDE asks first. fmGraph starts a model that has no boards of its own with its templates\' boards.' },
      { see: ['template-versions', 'recipes', 'library-packs'] },
    ] },
  { id: 'template-versions', group: 'templates', title: 'Template versions and updating a canvas',
    keywords: 'version update new version canvas linked ⬆ not now older unlink remove old versions tidy clean up',
    summary: 'Improve a template as new versions; canvases made from it offer the update.',
    body: [
      { p: 'In {cmd:openTemplates}, select a template and choose ⤴ Save as new version: the open canvas becomes its next version, with a short note on what changed.' },
      { p: 'A canvas made from a template remembers it. When a newer version exists, a bar above the canvas says so and its tab shows ⬆.' },
      { p: 'Update this canvas… rebuilds it from the new version and keeps the input values you typed. Not now hides the bar until an even newer version appears.' },
      { p: '{cmd:updateCanvasTemplate} can also go back to an older version. {cmd:unlinkCanvasTemplate} makes a canvas forget its template.' },
      { p: 'To tidy up, select a template and choose 🧹 Remove old versions beside its name: every version but the latest goes. 🧹 Remove older versions under the list, or {cmd:removeOldTemplateVersions}, does the same for every template. A version still in use stays — one a canvas in the open model is linked to, one a system template\'s canvas is linked to, or one a recipe is pinned to — and the question says which and why. The latest version always stays, so version numbers are never used twice.' },
      { see: ['templates', 'recipes'] },
    ] },
  { id: 'recipes', group: 'templates', title: 'Recipes',
    keywords: 'recipe build parts three statements combine templates together nested inside recipe of recipes',
    summary: 'Several canvas templates put together, built in one go.',
    body: [
      { p: 'A recipe lists canvas templates to build together, for example Income Statement + Balance Sheet + Cash Flow. In {cmd:openTemplates}, choose + New Recipe…, pick the parts, and choose the latest or a fixed version of each.' },
      { p: 'Build adds one canvas per part, and plugs and sockets connect them by name. A part already in your model is skipped, ticked by default.' },
      { p: 'Build warns about sockets that nothing feeds.' },
      { p: 'A part can also be another recipe: it is built in its place, with its own parts, so a full model can be made from smaller recipes. The recipe\'s details list the canvases each recipe inside builds. A recipe can\'t contain itself, even through others; fmIDE won\'t offer one that would.' },
      { see: ['templates', 'plugs-sockets'] },
    ] },

  // ---------- Functions ----------
  { id: 'functions', group: 'functions', title: 'Your own functions',
    keywords: 'function formula write define margin library version',
    summary: 'Write a formula once, like Margin(Revenue, Cost) = (Revenue - Cost) / Revenue, and reuse it.',
    body: [
      { steps: [
        'Open {cmd:openFunctions} and choose + New Function….',
        'Type the whole definition: the name, the inputs in brackets, = and the formula. The editor checks it as you type.',
        'Save. The function joins your library.',
      ] },
      { p: 'Formulas can use + − * / ^, brackets, comparisons, MIN MAX AVERAGE ABS MOD IFERROR IF AND OR NOT ROUND and PERIOD(), and your other functions.' },
      { p: 'Functions have versions, like templates: Edit as new version… saves a change.' },
      { see: ['function-nodes', 'library-packs'] },
    ] },
  { id: 'function-nodes', group: 'functions', title: 'Using a function on the canvas',
    keywords: 'function node insert update ⬆ inputs box',
    summary: 'Put a function on the canvas as a box with one input per argument.',
    body: [
      { p: '{cmd:insertFunction} adds a box titled ƒ Name, with its inputs on the left and its result on the right. Draw arrows onto the inputs.' },
      { p: 'The model keeps its own copy of the function, so it works the same for anyone you send it to.' },
      { p: 'When your library has a newer version, the box shows ⬆: click it to update this box or every use. {cmd:updateFunction} does the same for the selected box.' },
      { see: ['functions'] },
    ] },

  // ---------- Sharing and the library ----------
  { id: 'library-packs', group: 'sharing', title: 'Library packs',
    keywords: 'library pack share export import author licence CC BY',
    summary: 'Share templates, recipes and functions with other people as one file.',
    body: [
      { p: '{cmd:saveLibraryPack} puts the templates, recipes and functions you pick into one file, with a title and your name. Everything in a pack is shared under the CC BY 4.0 licence, so share only what is yours.' },
      { p: 'The pack is saved in your Downloads folder, named after its id (a long code ending in .fmide-pack.json). Keep that name. Send the file to a colleague by email or a shared folder, or share it with everyone in the community library: {cmd:shareLibraryPack}, step by step in "Share your pack in the community library".' },
      { p: '{cmd:openLibraryPack} shows a pack before anything is added: who made it, and for each item whether it is new or already in your library. Untick what you don\'t want. Nothing of yours is replaced.' },
      { see: ['share-library-pack', 'browse-library', 'templates', 'functions'] },
    ] },
  { id: 'share-library-pack', group: 'sharing', title: 'Share your pack in the community library',
    keywords: 'share publish upload submit community library github account sign up pull request fork propose changes terms review',
    summary: 'Put your templates in the community library, so anyone can add them from Browse Library. Every step, no GitHub experience needed.',
    body: [
      { p: 'The community library lives on GitHub, a free website where people share files. You don\'t need to know anything about it: follow these steps. The first time takes about fifteen minutes, mostly making an account. fmIDE never sends anything itself: you upload your pack file in your web browser.' },
      { p: 'You need: your pack file, an internet connection, and an email address for a free GitHub account.' },
      { p: 'Step 1 — Save your pack' },
      { steps: [
        'Choose {cmd:saveLibraryPack}.',
        'Give it a title, your name as the author (use the same name every time you share), a short description and a few tags.',
        'Tick the templates, recipes and functions to share. Share only what is yours: everything in a pack is shared under the CC BY 4.0 licence, so anyone may use and change it, with credit to you.',
        'Press Save Pack. The file goes to your Downloads folder. Its name is a long code ending in .fmide-pack.json. Don\'t rename it: the library finds packs by that name.',
        'A window opens with the next steps. Keep it open, or come back to it any time with {cmd:shareLibraryPack}.',
      ] },
      { p: 'Step 2 — Make a free GitHub account (the first time only)' },
      { steps: [
        'Go to github.com in your web browser and choose Sign up.',
        'Enter your email address, a password and a user name, and follow the steps on the screen. GitHub emails you a code to check your address.',
        'Already have an account? Just sign in.',
      ] },
      { p: 'Step 3 — Upload your pack' },
      { steps: [
        'In fmIDE, choose {cmd:shareLibraryPack} and press Open the upload page. GitHub opens in a new tab. (Or type this address into your browser: https://github.com/taroyamakatrmttm-star/fmide-library/upload/main/packs)',
        'Sign in if GitHub asks.',
        'If GitHub says you need your own copy of the library to make changes (a "fork"), press the green Fork this repository button. It is free, and you never need to look at it again. You may need to open the upload page again afterwards.',
        'Drag your pack file from your Downloads folder onto the page. Or press choose your files and pick it.',
        'Wait until the file\'s name appears under the box. Leave the other boxes as they are.',
        'Press the green Propose changes button. (If you see Commit changes instead, choose "Create a new branch for this commit", then press Propose changes.)',
      ] },
      { p: 'Step 4 — Send it for review' },
      { steps: [
        'GitHub shows a page called "Comparing changes". Press the green Create pull request button. A "pull request" is GitHub\'s name for "please add my file".',
        'A form opens. Under "What this pack holds", you may write a sentence about what your templates are for. Don\'t change anything else.',
        'Press Create pull request again, at the bottom of the form.',
        'On the page that opens, find "Submission terms" and read them (the link opens them). They say the items are yours to share and that you share them under CC BY 4.0.',
        'Tick the box beside "I have read the submission terms". It is ticked as soon as you click it; nothing else to press.',
      ] },
      { p: 'Step 5 — The automatic check and the review' },
      { steps: [
        'Within a few minutes, a comment called "Library check" appears on your pull request.',
        'It should say PASSED ✅. It also lists the library\'s records for your pack (who shared it, and when), "added automatically when the pull request is merged". You don\'t need to do anything with them: the library writes them itself when your pack is accepted.',
        'If it says "The submission terms are not ticked", tick the box from Step 4. The check runs again by itself.',
        'If it lists another problem, write a comment on your pull request asking for help (the box at the bottom of the page, then Comment). Or save the pack again in fmIDE and upload the new file the same way.',
        'The maintainer reviews every pack by hand. GitHub emails you when your pack is accepted, or if there is a question.',
      ] },
      { p: 'Step 6 — See it in the library' },
      { p: 'Once accepted, your pack appears on fmIDE\'s website, in {cmd:browseLibrary} and on the /library pages, usually within a few days. People who add your templates see you as their author.' },
      { tip: 'To share an improved version later: in {cmd:openTemplates}, save the new version (⤴ Save as new version), then save a new pack and upload it the same way. A pack is never changed once it is in the library. Only the account that first shared a template or function can add new versions of it, so nobody else can publish a "new version" of yours.' },
      { tip: 'An fmGraph board shares with its template: attach it to the template first (in fmGraph, Boards ▾ → Attach to template…), then save and share the pack here.' },
      { see: ['library-packs', 'browse-library', 'template-versions'] },
    ] },
  { id: 'browse-library', group: 'sharing', title: 'Browsing the library',
    keywords: 'browse library community catalogue download online',
    summary: 'Find packs other people shared, on fmIDE\'s website.',
    body: [
      { p: 'On fmIDE\'s website, {cmd:browseLibrary} lists the community\'s packs, with a search box and filters. Preview and add… opens the usual preview before anything is added.' },
      { p: 'A canvas or system template that carries an fmGraph board has 📈 Try in fmGraph: fmGraph opens the template with its board, so you can move its sliders before adding it. Nothing is added to your library or your document, and fmGraph keeps nothing; Show fmIDE\'s model there goes back to your own.' },
      { p: 'It needs a connection. fmIDE opened from a file on your computer never connects to anything: download packs from the website\'s /library page instead, and open them with {cmd:openLibraryPack}.' },
      { see: ['library-packs', 'share-library-pack', 'fmgraph'] },
    ] },

  // ---------- Files and saving ----------
  { id: 'documents', group: 'files', title: 'Saving and opening documents',
    keywords: 'save open new recent document file fmide autosave recover',
    summary: 'Your work is a .fmide document: New, Open, Save, Save As and Open Recent.',
    body: [
      { p: '{cmd:saveDocument} (Ctrl+S, or Cmd+S on a Mac) saves your model as a .fmide file, and {cmd:openDocument} (Ctrl+O) opens one. {cmd:openRecent} lists the last ten.' },
      { p: 'In Chrome and Edge, Save writes straight back to the file. Other browsers download a copy each time.' },
      { p: 'fmIDE also saves your work in the browser as you go. After a crash it comes back with your changes and offers to save them.' },
      { p: 'A • in the window title means there are unsaved changes.' },
      { see: ['other-files'] },
    ] },
  { id: 'other-files', group: 'files', title: 'Other files: systems, modules, workspaces, preferences',
    keywords: 'system module workspace export import preferences json file',
    summary: 'The other files fmIDE reads and writes, and what each is for.',
    body: [
      { p: 'A system file ({cmd:saveSystem}) is the whole model, without your templates. {cmd:loadSystem} replaces the model with one, and {cmd:addSystem} adds one alongside.' },
      { p: 'A module ({cmd:saveModule}) is one canvas; {cmd:loadModule} adds its boxes to the current canvas.' },
      { p: 'A workspace ({cmd:exportWorkspace}) is the model with your templates, formats and macros; {cmd:importWorkspace} opens one.' },
      { p: 'Preferences ({cmd:exportPreferences}) are your shortcuts and ribbon, to take to another computer.' },
      { p: 'ExcelExporter reads a document, a system or a workspace.' },
      { see: ['documents', 'to-excel'] },
    ] },

  // ---------- Formatting ----------
  { id: 'formats', group: 'format', title: 'Formats and format roles',
    keywords: 'format colour color fill font border number format preset role style 🎨 excel style',
    summary: 'How rectangles look on the canvas, and the number formats that go to Excel.',
    body: [
      { p: '{cmd:openFormats} holds format presets. Two of them are roles:' },
      { steps: [
        'Inputs: every input rectangle (the numbers you type).',
        'Calculations: every rectangle fed by an arrow.',
      ] },
      { p: 'Change a role and every rectangle in it follows. 🎨 on a rectangle gives it its own look instead.' },
      { p: 'Only number formats go to Excel: a rectangle\'s own, or its role\'s. How cells look in Excel (fills, fonts, borders) is set in ExcelExporter (⚙ Settings → Excel Style), and is kept there for every model you export.' },
      { see: ['to-excel'] },
    ] },

  // ---------- To Excel ----------
  { id: 'to-excel', group: 'excel', title: 'From fmIDE to Excel',
    keywords: 'excel export exporter workbook xlsx formulas generate download',
    summary: 'Turn the model into an Excel workbook with live formulas.',
    body: [
      { steps: [
        'Open {cmd:openExcelExporter}. It opens in its own window (or tab) with the model you have open — no need to save first.',
        'Arrange the tabs and rows if you like.',
        'Press ⬇ Generate .xlsx, at its top right.',
      ] },
      { p: 'After changing the model here, choose File → ↻ From fmIDE in ExcelExporter (or {cmd:openExcelExporter} again) to load it as it is now. A change to numbers keeps your layout there; adding or deleting a rectangle starts a new layout, as loading a changed file does (a module\'s tab keeps its remembered layout). The Excel layouts your canvas templates carry go along too.' },
      { tip: 'ExcelExporter can also open a saved .fmide document or system file on its own (File → Open Model…).' },
      { p: 'The workbook calculates exactly as fmIDE does. Where it can\'t (for example a loop, or an alias to a rectangle that was deleted), a yellow list above the Generate button says where, before you download.' },
      { see: ['formats', 'other-files'] },
    ] },

  { id: 'fmgraph', group: 'start', title: 'See how a value moves the model (fmGraph)',
    keywords: 'fmgraph graph chart bar slider what if impact sensitivity dependency',
    summary: 'Bars show rectangles; sliders change inputs; the bars move as you slide.',
    body: [
      { p: 'fmGraph is a companion to fmIDE. It shows rectangles as bars, one per period, and lets you change input rectangles with sliders. Move a slider and every bar that depends on that input moves with it; the bars it reaches light up.' },
      { steps: [
        'Open {cmd:openFmGraph}. It opens in its own window (or tab) with the model you have open — no need to save first.',
        'Add a slider on an input and a bar on a result (+ Slider, + Bar).',
        'Move the slider.',
      ] },
      { p: 'fmGraph never changes your model: a slider is a "what if", and Reset puts the number back. After changing the model here, press ↻ From fmIDE in fmGraph (or {cmd:openFmGraph} again) to see it as it is now.' },
      { p: 'The boards you set up in fmGraph — its bars, charts and sliders — are kept in your document: a change to them there marks the document unsaved here, and {cmd:saveDocument} keeps them with the model. Opening the document brings them back, ahead of the ones fmGraph remembered in the browser. Moving a slider changes nothing.' },
      { tip: 'fmGraph can also open a saved .fmide file on its own, and has its own Help (❓).' },
      { see: ['to-excel'] },
    ] },

  // ---------- Working faster ----------
  { id: 'launcher-shortcuts', group: 'faster', title: 'Command Launcher and keyboard shortcuts',
    keywords: 'launcher search command keyboard shortcut keys ctrl+k keytips alt',
    summary: 'Run any command by typing its name, give commands your own keys, and use KeyTips.',
    body: [
      { p: '{cmd:openLauncher} (Ctrl+K, or Cmd+K on a Mac) finds any command, action, macro or help topic as you type. Press Enter to run it.' },
      { p: '{cmd:openShortcuts} lets you give any command its own keys.' },
      { p: 'Tap Alt to show KeyTips: a letter on every ribbon tab and button, so you can press the letters instead of clicking.' },
      { see: ['customize-ribbon', 'macros'] },
    ] },
  { id: 'customize-ribbon', group: 'faster', title: 'Customising the ribbon',
    keywords: 'ribbon customize tabs groups quick access toolbar qat collapse keytips',
    summary: 'Arrange the ribbon\'s tabs, groups and buttons your way.',
    body: [
      { p: '{cmd:customizeRibbon} adds, removes and moves tabs, groups and buttons, including your macros, and the Quick Access Toolbar at the top left. It also sets the KeyTips key.' },
      { p: '{cmd:toggleRibbon} (Ctrl+F1) folds the ribbon away to make room.' },
      { see: ['launcher-shortcuts'] },
    ] },
  // ---------- Macros ----------
  { id: 'macros', group: 'macros', title: 'Macros',
    keywords: 'macro record automate repeat steps builder run script shortcut ribbon',
    summary: 'Record or build a series of steps and run it again with one click.',
    body: [
      { p: 'A macro is a list of steps that fmIDE runs for you, in order. It runs as one step you can undo, and if any step fails it stops and puts everything back, so a macro never leaves a model half changed.' },
      { p: '{cmd:toggleRecord} records what you do: adding, connecting, typing, moving, formatting, switching canvases, inserting templates. Press it again (or the red Recording pill) to stop, and the steps become a macro. Before you start you can choose to refer to the selected nodes as @sel, so the macro works on whatever is selected when it runs, and to record positions relative to the selection, so it can build anywhere.' },
      { p: '{cmd:openMacros} shows your macros step by step: change them, add steps, run them, export and import them. {cmd:runLastMacro} runs the last one again.' },
      { p: 'Give a macro a shortcut in Keyboard Shortcuts (category Macros), or tick Show on Ribbon to give it a button under Macros › My Macros.' },
      { see: ['macro-steps', 'macro-variables', 'macro-references', 'macro-reliable', 'macro-errors'] },
    ] },
  { id: 'macro-steps', group: 'macros', title: 'Building a macro step by step',
    keywords: 'macro builder action group repeat loop for each set var variable comment indent disable step',
    summary: 'What + Action, + Group, + Repeat, + For each, + Set var and + Comment do.',
    body: [
      { p: 'In {cmd:openMacros} the list on the left holds your macros. The middle shows the chosen macro\'s steps as a tree, and the right side edits the step you select. A new step goes after the selected one, or inside it when it is a group or loop.' },
      { steps: [
        '+ Action: one fmIDE action, such as createRect (add a rectangle), connect, setValue or switchCanvas (go to a canvas). Choose it under Action and fill in its boxes; a blank box uses its default. An action that makes something has a "Save result as" box, which the builder fills in for you ($r1 for nodes, $c1 for a canvas, $t1 for Insert Template), so later steps can refer to what it made.',
        '+ Group: a labelled folder for keeping a long macro tidy. It does nothing by itself: the steps inside it run in order, as if it were not there.',
        '+ Repeat: runs the steps inside it a number of times (Times: 5, or $periods for once per period). Its variable, $i unless you rename it, counts 1, 2, 3… — use it in the steps inside, such as y = 100 + $i*80 or a name Line ${i}.',
        '+ For each: runs the steps inside it once for each node in a list (Nodes: @sel, the selection, unless you change it). Its variable, $item, is that node: write $item in a step\'s node box. $itemIndex counts 1, 2, 3…',
        '+ Set var: gives a variable a value for later steps — a number or expression (100 + $i*80), another variable ($r1), or text (Total ${i}).',
        '+ Comment: a note in the list. It does nothing.',
      ] },
      { p: 'Move a step into the group or loop above it with → (Alt+→) and out again with ← (Alt+←), or drag it onto the middle of a group. ↑ and ↓ move it, ⧉ duplicates it, ⊘ switches it off without deleting it, 🗑 deletes it. Every step can carry a Note.' },
      { p: '▶ Run selected step runs just that step, to try it, and selects the next one, so pressing it again steps through the macro. The variables the steps already run saved are kept for the next step, as in a whole run, until you close the Macro Builder or choose another macro. ▶ Run macro runs them all.' },
      { p: 'A step marked ⚠ in the list reads a variable that no step before it saves — usually because the step that saved it was deleted or changed. Point it at a variable an earlier step saves before you run the macro.' },
      { tip: 'Record first, then open the Macro Builder to tidy up: the recorder writes finished steps that you can change, put in loops or switch off.' },
      { see: ['macros', 'macro-variables', 'macro-references'] },
    ] },
  { id: 'macro-variables', group: 'macros', title: 'Variables, loops and expressions',
    keywords: 'macro variable $ $i $item $periods $period list index expression round min max text ${}',
    summary: 'Named values ($i, $item, $r1) and the expressions a number box takes.',
    body: [
      { p: 'A variable is a named value that a step can use, written with $ in front: $i, $item, $r1. They come from:' },
      { steps: [
        'A Repeat\'s counter ($i: 1, 2, 3…) and a For each\'s node ($item, and $itemIndex: 1, 2, 3…).',
        'A Set var step.',
        'An action\'s "Save result as": what it made — a node ($r1), several nodes ($r1, a list), a canvas ($c1), or what Insert Template made ($t1).',
        'Two that are always there: $periods, how many periods the model has, and $period, the period you are viewing (from 1).',
      ] },
      { p: 'A variable holding a list takes a number in brackets, counted from 0: $r1[0] is the first item, $r1[2] the third. Add Many Rectangles saved as $r1 gives one item per rectangle; a recipe inserted as $t1 gives one canvas per part.' },
      { p: 'Every number box takes an expression: + - * / % and brackets, variables, and min, max, round, floor, ceil and abs — for example 100 + $i*80, $periods - 1 or round($x/2).' },
      { p: 'In text, ${…} puts in a variable or an expression: a name Line ${i} gives Line 1, Line 2…, and Year ${2024 + i} gives Year 2025, Year 2026…' },
      { tip: 'Five input rows in one go: + Repeat with Times 5, and inside it + Action createRect with name Line ${i} and y 100 + $i*80.' },
      { see: ['macro-steps', 'macro-references'] },
    ] },
  { id: 'macro-references', group: 'macros', title: 'Referring to nodes, canvases and templates',
    keywords: 'macro reference id #id #n #c canvas node @sel @cur @all :: copy reference name duplicate template family version',
    summary: 'How a step names what it works on: names, ids (#n12, #c3), @sel, saved variables.',
    body: [
      { p: 'A step names what it works on in a box. For nodes:' },
      { steps: [
        'Revenue — the rectangle named Revenue on the canvas (capitals don\'t matter). An alias or a block goes by the name it shows.',
        '#n12 — a node by its id.',
        '@sel, @sel[0] — the selection when the macro started, or its first node. @cur is the selection as it is now, while the macro runs.',
        '@all — every node on the canvas; @all[3] is its fourth node (counted from 0, leaving out the automatic plug aliases).',
        '$r1, $r1[0] — a node an earlier step made and saved.',
        'Loans::Interest — the rectangle Interest on the canvas Loans; $t1[0]::Interest is it on the canvas a step made. A box for several nodes takes a list: Revenue, Cost.',
      ] },
      { p: 'For canvases: a name (Loans), an id (#c3), or a canvas an earlier step made ($c1, $t1[0]).' },
      { p: 'An id is a node\'s or canvas\'s own label inside the model: nodes #n…, canvases #c…. It stays the same when you rename them, so it works when two share a name. To find one: hover over a canvas tab to see its id; select nodes and use {cmd:copyReference}, which copies how a step refers to them — the name, or the id when the name is used twice — ready to paste in a box. With nothing selected it copies the canvas\'s. On a tablet, hold a node and choose Copy reference. The step boxes also offer the selected nodes, and canvases sharing a name, by id.' },
      { p: 'Ids belong to one model: run in another model, a step using #n12 won\'t find it, or finds a different node. Names, @sel and saved variables work in any model.' },
      { p: 'Templates: Name (the latest version), Name@3 (version 3) or Name@latest. When two template families share a name, use the family\'s ID instead of the name: the message that stops the macro lists them.' },
      { see: ['macro-reliable', 'macro-errors', 'macro-variables'] },
    ] },
  { id: 'macro-reliable', group: 'macros', title: 'Macros that work every time',
    keywords: 'macro recorded fails differs state duplicate name canvas template recipe skip @all note warning relative selection paste',
    summary: 'A macro runs in the model as it is then. How recording copes, and what a ⚠ note means.',
    body: [
      { p: 'A macro runs in the model as it is when you run it, which may not be how it was when you recorded it. The recorder picks references that keep working:' },
      { steps: [
        'What a step made is kept in its variable. A canvas Insert Template adds is $t1 (several: $t1[0], $t1[1]…), so a later Go to Canvas finds the new one even when another canvas has the same name.',
        'A recipe gives one canvas per part, in order, so $t1[1] is always the second part — also when a part already here was skipped (it is then that canvas).',
        'Skipping the parts of a recipe that are already here is recorded as that rule, so the macro skips what is here when it runs.',
        'A node a template made with no name of its own, such as an operator, is referred to by its place on that canvas (@all[3]).',
      ] },
      { p: 'Where it can\'t be sure, the recorder puts a ⚠ note on the step and says so when you stop recording. A note means: a node of this model referred to by its id (another model won\'t have it); a node made while recording that no step saved; an automatic plug alias (it gets a new id whenever plugs are worked out); a template\'s node referred to by its place (check it if the template changes); or a Paste whose Copy wasn\'t recorded (it pastes whatever was copied last).' },
      { p: 'Undo while recording takes back the steps recorded since the change it undoes, and only those: undoing something that was never a step (a box picked up and put back where it was) leaves the recorded steps alone.' },
      { p: 'Other things that can be different when it runs:' },
      { steps: [
        'The selection: a macro using @sel needs the nodes selected first.',
        'Names: a canvas or rectangle renamed or deleted since; or a name now used twice — rename one, or use the id.',
        'The canvas you are on: the macro starts on the current canvas. If it should start somewhere else, record a Go to Canvas step first.',
        'Positions: x and y are where you put things. Tick Relative positions to build next to the selection (or the middle of the view) instead.',
      ] },
      { see: ['macro-references', 'macro-errors'] },
    ] },
  { id: 'macro-errors', group: 'macros', title: 'When a macro stops',
    keywords: 'macro error stopped nothing was changed message fix more than one canvas named no rectangle selection variable no value',
    summary: 'What "Stopped — nothing was changed" means, and what to do about each message.',
    body: [
      { p: '"Stopped — nothing was changed" means a step could not run, so fmIDE put the model back as it was before the macro. The message names the step (its action and boxes) and why; in the Macro Builder that step is marked in red.' },
      { steps: [
        'More than one canvas is named "…" (#c3, #c7): rename one (double-click its tab), or write the id of the one you mean in the step\'s Canvas box. If an earlier step made that canvas, use its variable instead ($t1[0] or $c1): it always finds the canvas the macro made.',
        '2 rectangles on "…" are named "…": rename one, or write the id of the one you mean (select it and use {cmd:copyReference}).',
        'There is no canvas called "…" / no rectangle named "…": it was renamed or deleted, or the macro is running on another canvas than you expected.',
        'Nothing was selected when the macro started: select the nodes it should work on, then run it again.',
        '$t1 holds 2 canvases or nodes — say which one: write $t1[0], $t1[1]….',
        'No step in this macro saves $t2: the step that saved it was deleted or changed (or lost while recording — see Macros that work every time). The message lists the variables the steps do save; point the step at one of them. The Macro Builder marks such a step with ⚠ before you run it.',
        '$t1 is saved by an earlier step that hasn\'t run in this step-by-step run: you started ▶ Run selected step in the middle. Select the first step and step through from there, or use ▶ Run macro.',
        'Variable $x has no value yet: the step that sets it has not run — it is switched off, comes later, or is inside a loop that ran no times.',
        'More than one template family is named "…": write the family\'s ID (listed in the message) instead of the name, or rename one in Templates.',
      ] },
      { tip: 'Select a step and press ▶ Run selected step to try it on its own.' },
      { see: ['macro-references', 'macro-reliable'] },
    ] },

  // ---------- Touch ----------
  { id: 'touch', group: 'touch', title: 'Using fmIDE on a tablet',
    keywords: 'touch tablet ipad finger pen hold press tap double-tap menu pinch zoom',
    summary: 'Drag with a finger; press and hold for a menu; double-tap to edit.',
    body: [
      { p: 'Drag boxes with a finger. Tap a box to show its dots, then drag from a dot to draw an arrow.' },
      { p: 'Press and hold a box for its menu, which has:' },
      { steps: [
        'Draw an arrow from here (then tap the target).',
        'Make an alias.',
        'Duplicate.',
        'Add to or remove from the selection.',
        'Edit, Properties and Delete.',
      ] },
      { p: 'One finger on empty canvas scrolls. Press and hold there, then drag, to select with a box.' },
      { p: 'Pinch with two fingers to zoom the canvas around the point between them; move both fingers together to move around. A pinch that ends close to 100% settles at 100%.' },
      { p: 'Double-tap does what a double-click does.' },
      { see: ['arrows', 'arranging'] },
    ] },
];

const COMMAND_HELP = {
  undo: 'Takes back your last change.',
  redo: 'Puts back the change you just undid.',
  copy: 'Copies the selected boxes, with the arrows between them.',
  cut: 'Copies the selected boxes and removes them.',
  paste: 'Pastes what you copied into free space on this canvas.',
  deleteSel: 'Deletes the selected boxes or arrow.',
  selectAll: 'Selects every box on this canvas.',
  deselect: 'Clears the selection and closes any open picker.',
  addRect: 'Adds a rectangle, ready to type its name, value and unit.',
  addManyRects: 'Adds many rectangles at once: type or paste a list of names, one rectangle each, laid out evenly.',
  addOperator: 'Adds an operator and asks which one: + − × ÷ and more.',
  addAlias: 'Adds an alias: a stand-in that shows another rectangle\'s value.',
  addBlock: 'Adds another canvas as a block: one box with its inputs and outputs.',
  addPeriodShift: 'Adds a period shift, which passes on a value from another period (last period by default).',
  newCanvas: 'Adds a new, empty canvas tab.',
  renameCanvas: 'Renames the current canvas.',
  deleteCanvas: 'Deletes the current canvas and everything on it.',
  clearCanvas: 'Removes every box and arrow on the current canvas.',
  clearAll: 'Removes every canvas, leaving one empty canvas.',
  moveCanvasLeft: 'Moves the current canvas tab one place to the left.',
  moveCanvasRight: 'Moves the current canvas tab one place to the right.',
  prevCanvas: 'Goes to the canvas tab on the left (from the first, to the last).',
  nextCanvas: 'Goes to the canvas tab on the right (from the last, back to the first).',
  alignLeft: 'Lines up the selected boxes on their left edges.',
  alignCenterH: 'Lines up the selected boxes on their centres, left to right.',
  alignRight: 'Lines up the selected boxes on their right edges.',
  alignTop: 'Lines up the selected boxes on their top edges.',
  alignCenterV: 'Lines up the selected boxes on their middles, top to bottom.',
  alignBottom: 'Lines up the selected boxes on their bottom edges.',
  distH: 'Spaces three or more selected boxes evenly from left to right.',
  distV: 'Spaces three or more selected boxes evenly from top to bottom.',
  evaluate: 'Works out every value in the model for the period shown.',
  prevPeriod: 'Shows the previous period.',
  nextPeriod: 'Shows the next period.',
  managePeriods: 'Adds, removes or renames the periods of the timeline.',
  saveSystem: 'Downloads the whole model as a system file (without your templates).',
  loadSystem: 'Replaces the model with one from a system file.',
  addSystem: 'Adds the canvases of a system file alongside the model.',
  saveModule: 'Downloads the current canvas as a module file.',
  loadModule: 'Adds the boxes of a module file to the current canvas.',
  exportWorkspace: 'Downloads the model with your templates, formats and macros.',
  importWorkspace: 'Replaces the model with a workspace file\'s, and adds its templates you don\'t have.',
  exportPreferences: 'Saves your shortcuts and ribbon to a file, for another computer.',
  importPreferences: 'Replaces your shortcuts and ribbon with those in a preferences file.',
  openTemplates: 'Opens your templates: search, add, save and manage them.',
  openFunctions: 'Opens your functions: write, change and manage them.',
  importFunctions: 'Adds the functions in a functions file to your library.',
  browseLibrary: 'Lists the packs people shared on fmIDE\'s website (needs a connection).',
  openLibraryPack: 'Previews a library pack file and adds the items you choose.',
  shareLibraryPack: 'Shows how to share a pack with everyone in the community library, and opens the library\'s upload page on GitHub.',
  saveLibraryPack: 'Saves templates, recipes and functions you pick as a pack to share.',
  insertFunction: 'Adds one of your functions to the canvas as a box.',
  updateFunction: 'Moves function boxes on an older version of their function to the latest one.',
  removeDuplicateTemplates: 'Finds templates that are copies of each other and lets you keep one of each.',
  removeOldTemplateVersions: 'Removes the older versions of every template, keeping the latest of each and any version still in use, after asking.',
  clearAllTemplates: 'Deletes every template in your library, after asking.',
  updateCanvasTemplate: 'Rebuilds this canvas from another version of its template, keeping your inputs.',
  unlinkCanvasTemplate: 'Makes this canvas forget the template it came from.',
  openFormats: 'Opens the format presets and roles that decide how rectangles look on the canvas.',
  newDocument: 'Starts a new, empty document.',
  openDocument: 'Opens a .fmide document.',
  saveDocument: 'Saves the document.',
  saveDocumentAs: 'Saves the document under a new name.',
  openRecent: 'Lists the documents you opened lately.',
  openExcelExporter: 'Opens ExcelExporter, which turns your model into an Excel workbook.',
  openFmGraph: 'Opens fmGraph with this model: bars and sliders that show how one value moves the rest.',
  installApp: 'Installs fmIDE as an app with its own window, working offline.',
  openLauncher: 'Finds any command, macro or help topic as you type its name.',
  openShortcuts: 'Shows every keyboard shortcut and lets you change them.',
  toggleRibbon: 'Folds the ribbon away, or opens it again.',
  customizeRibbon: 'Arranges the ribbon\'s tabs, groups and buttons, and the KeyTips key.',
  openHelp: 'Opens this Help panel: search, topics and step-by-step guides.',
  openWhatsNew: 'Lists every update to fmIDE, newest first: what changed, why, and how to use it.',
  zoomIn: 'Zooms the canvas in one step, keeping the middle of the view in place.',
  zoomOut: 'Zooms the canvas out one step, to see more of the model.',
  zoomReset: 'Shows the canvas at its real size, 100%.',
  zoomFit: 'Zooms so that everything on this canvas fits on the screen.',
  zoomSelection: 'Zooms so that the selected boxes fill the screen.',
  openMacros: 'Opens the Macro Builder, to make and change macros.',
  toggleRecord: 'Records what you do as a macro; press again to stop.',
  runLastMacro: 'Runs the last macro you ran again.',
  copyReference: 'Copies how a macro step refers to the selected nodes (or, with nothing selected, this canvas): the name, or the id when the name is used twice.',
};

const OPERATOR_HELP = {
  add: 'adds up all its inputs.',
  subtract: 'subtracts, left to right: the first input minus the others.',
  multiply: 'multiplies all its inputs.',
  divide: 'divides, left to right: the first input by the others.',
  power: 'raises the first input to the power of the second.',
  mod: 'gives the remainder of the first input divided by the second.',
  le: 'gives 1 when the first input is at most the second, otherwise 0.',
  ge: 'gives 1 when the first input is at least the second, otherwise 0.',
  lt: 'gives 1 when the first input is less than the second, otherwise 0.',
  gt: 'gives 1 when the first input is greater than the second, otherwise 0.',
  abs: 'gives the value without its sign.',
  min: 'gives the smallest of its inputs.',
  max: 'gives the largest of its inputs.',
  average: 'gives the average of its inputs.',
  iferror: 'gives its first input, or its second where the first has an error.',
  period: 'gives the period number: 1, 2, 3…',
  if: 'gives "then" when the condition is not 0, otherwise "else".',
  eq: 'gives 1 when its two inputs are equal, otherwise 0.',
  ne: 'gives 1 when its two inputs differ, otherwise 0.',
  and: 'gives 1 when all its inputs are not 0, otherwise 0.',
  or: 'gives 1 when any of its inputs is not 0, otherwise 0.',
  not: 'gives 1 for 0, and 0 for anything else.',
  round: 'rounds a value to a number of digits, like Excel\'s ROUND.',
  roundup: 'rounds a value away from zero, like Excel\'s ROUNDUP.',
  rounddown: 'rounds a value towards zero, like Excel\'s ROUNDDOWN.',
  ln: 'gives the natural logarithm of its input, like Excel\'s LN.',
  exp: 'gives e raised to the power of its input, like Excel\'s EXP.',
  sqrt: 'gives the square root of its input, like Excel\'s SQRT.',
  int: 'rounds its input down to a whole number, like Excel\'s INT.',
  trunc: 'cuts the fraction off its input, like Excel\'s TRUNC.',
  choose: 'gives the choice its index picks (2 gives choice 2), like Excel\'s CHOOSE.',
};
